import numpy as np

from . import Surface
from ...grids import Rmesh3d, R3grid
from ...core.netcdf import NetcdfMixin



def decode_header(header, kwargs):
    description = header
    vlabel = ""

    if ';' in header:
        ssplit = header.split(';')
        description = ssplit[0]
        for s in ssplit[1:]:
            if not '=' in s:
                continue
            key, value = s.split('=', maxsplit=1)
            if key.lstrip().rstrip() == "vlabel":
                vlabel = value.lstrip('" ').rstrip('" ')
                if not "vlabel" in kwargs and vlabel:
                    kwargs["vlabel"] = vlabel

            if key.lstrip().rstrip() == "phi0":
                kwargs['phi0'] = float(value)

            if key.lstrip().rstrip() == "symmetry":
                kwargs['symmetry'] = int(value)

    if not "description" in kwargs:
        kwargs["description"] = description.lstrip()
    return kwargs



class Axisurf(Surface, NetcdfMixin):
    """
    An axisymmetric surface :math:`\\mathbf{S}(u,v)` that is generated by rotating a polygonal outline round the z-axis. The v-coordinates maps onto the outline in the R-Z plane, and :math:`\\varphi = \\varphi_0 + \\frac{2 \\, \\pi}{\\mathrm{symmetry}} \\cdot u`.

    .. image:: axisurf.png
        :width: 90%

    **Parameters:**

    :r:     1-D array of R-coordinates.

    :z:     1-D array of Z-coordinates.

    :v:     Optional 1-D array for poloidal coordinate along surface contour.

    **Metadata:**

    :phi0:          Toroidal offset for definition of surface coordinate *u*.

    :symmetry:      Toroidal symmetry for definition of surface coordinate *u*.

    :description:   Surface label.

    :units:         Units for R- and Z-coordinates.

    :vlabel:        Label for v-coordinate.
    """

    def __init__(self, r, z, v=None, phi0=0.0, symmetry=1, **metadata):
        super().__init__({"units": "m"} | metadata)
        self.r = np.asarray(r)
        self.z = np.asarray(z)
        if not self.r.size == self.z.size:
            raise(ValueError("incompatible array sizes for *r* and *z*"))
        self._v = v
        self.phi0 = phi0
        self.symmetry = symmetry


    @property
    def nv(self):
        """
        Number of nodes in poloidal direction.
        """
        return self.v.size


    @property
    def v(self):
        if self._v is not None:
            return self._v

        # arc length along contour
        n = self.r.shape[0]
        v = np.zeros(n)
        for i in range(1,n):
            dr = self.r[i] - self.r[i-1]
            dz = self.z[i] - self.z[i-1]
            v[i] = v[i-1] + np.sqrt(dr**2 + dz**2)
        return v


    def grid(self, nphi, nsym=1, phi0=0.0):
        """
        :class:`R3grid` representation of surface.
        """
        return R3grid.cylindrical(self.rmesh3d(nphi, nsym, phi0), length_units=self.units)


    def rmesh3d(self, nphi, nsym=1, phi0=0.0):
        """
        :class:`Rmesh3d` representation of surface with toroidal resolution *nphi*.
        """

        phi = np.linspace(phi0, phi0 + 360.0 / nsym, nphi)
        return Rmesh3d(phi, self.v, self.r, self.z, "Toroidal Angle [deg]", self.vlabel)


    @classmethod
    def new(cls, n, **kwargs):
        """
        Allocate new Axisurf object with poloidal resolution *n*.
        """

        r = np.zeros(n)
        z = np.zeros(n)
        v = np.zeros(n)
        return cls(r, z, v, **kwargs)


    @classmethod
    def loadtxt(cls, filename, fallback_v="arclength", **kwargs):
        """
        Load Axisurf object from file *filename*.
        """

        with open(filename, 'r') as f:
            header = f.readline().lstrip("# ").strip()
        kwargs = decode_header(header, kwargs)

        d = np.loadtxt(filename)
        # implicit definition of poloidal coordinate (arclength)
        if d.shape[1] == 2:
            if fallback_v == "arclength":
                return cls(d[:,0], d[:,1], vlabel="Arclength along surface contour", **kwargs)
            elif fallback_v == "index":
                v = np.arange(d.shape[0]) / (d.shape[0] - 1)
                return cls(d[:,0], d[:,1], v, **kwargs)
            else:
                raise(NotImplementedError(f"fallback_v = {fallback_v}"))

        # explict definition of poloidal coordinate
        elif d.shape[1] == 3:
            return cls(d[:,0], d[:,1], d[:,2], **kwargs)

        # invalid format
        else:
            raise(RuntimeError("invalid format of Axisurf file {}".format(filename)))


    @classmethod
    def _readnc(cls, nc):
        """Read from netcdf file."""
        metadata = cls.readnc_metadata(nc)
        nv = nc.dimensions["nv"]
        rz = nc['rz'][:]
        v = nc['v'][:]
        return cls(rz[:,0], rz[:,1], v, **metadata)


    def savetxt(self, filename, header=""):
        """Save Axisurf object to text file."""
        if header == "":
            header = self.description
            if self.vlabel:
                header += f'; vlabel = "{self.vlabel}"'
            if self.phi0 != 0.0:
                header += f'; phi0 = {self.phi0}'
            if self.symmetry != 1:
                header += f'; symmetry = {self.symmetry}'

        if self._v is None:
            x = np.vstack((self.r, self.z))
        else:
            x = np.vstack((self.r, self.z, self.v))
        np.savetxt(filename, x.T, header=header)


    def _writenc(self, nc):
        """
        Save Axisurf to netcdf group.
        """
        nc.createDimension('dim_0002', 2)
        nc.createDimension('nv', self.nv)
        for key, value in self.metadata.items():
            setattr(nc, key, value)

        nc.createVariable('v', np.float64, ('nv',))
        nc.createVariable('rz', np.float64, ('nv', 'dim_0002'))
        nc['v'][:]  = self.v
        nc['rz'][:,0]  = self.r
        nc['rz'][:,1]  = self.z
